name: "Configure Java and Gradle"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:

    # Setup JDK 17 to build properly
    - name: set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    # Setup Gradle because without it, nothing happens
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # Build cache (incremental outputs)
    - name: Cache Gradle build-cache
      uses: actions/cache@v4
      with:
        path: ~/.gradle/build-cache-1
        key: ${{ runner.os }}-gradle-buildcache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-gradle-buildcache-

    # Kotlin compiler
    - name: Cache Kotlin compiler
      uses: actions/cache@v4
      with:
        path: ~/.gradle/kotlin
        key: ${{ runner.os }}-gradle-kotlin-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-kotlin-

    # Cache Konan (Kotlin/Native)
    - name: Cache Konan
      uses: actions/cache@v4
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-konan-

    # Cache npm (for JS/WASM builds)
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-npm-
