name: "Configure Java and Gradle"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:

    # Setup JDK 17 to build properly
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    # Setup Gradle because without it, nothing happens
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
