name: "Find modules that need to be validated and exported"
description: "Boilerplate steps"

outputs:
  modules:
    description: "List of all modules"
    value: ${{ steps.read-all-modules.outputs.modules }}

  android-modules:
    description: "List of android modules"
    value: ${{ steps.read-android-modules.outputs.modules }}

  multi-modules:
    description: "List of multiplatform modules"
    value: ${{ steps.read-multi-modules.outputs.modules }}

runs:
  using: "composite"
  steps:

    # Get modules that need to be published and validated
    - name: Load Modules
      id: load-modules
      shell: bash
      run: |
        ./gradlew :toolkit:publishModules

    # List of all modules that need to be published and validated
    - name: Read Modules
      id: read-all-modules
      shell: bash
      run: |
        MODULES=$(cat $PWD/toolkit/build/modules.txt)
        echo "modules=$MODULES" >> "$GITHUB_OUTPUT"

    # List of android modules that need to be published and validated
    - name: Read Android Modules
      id: read-android-modules
      shell: bash
      run: |
        MODULES=$(cat $PWD/toolkit/build/modules-android.txt)
        echo "modules=$MODULES" >> "$GITHUB_OUTPUT"

    # List of multiplatform modules that need to be published and validated
    - name: Read Multiplatform Modules
      id: read-multi-modules
      shell: bash
      run: |
        MODULES=$(cat $PWD/toolkit/build/modules-multi.txt)
        echo "modules=$MODULES" >> "$GITHUB_OUTPUT"
