name: setup-git-jdk-gradle
description: "Sets up this repository clone, the JDK and the gradle"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
