name: Pull Request

on:
  pull_request:
    branches:
      - master
      - 'release/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'config/**'
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - toolkit:delegate
          - toolkit:event-observer
          - toolkit:foldable
          - toolkit:recycler-adapter
          - toolkit:statemachine
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:lint

      - name: Detekt ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:detekt

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        module:
          - toolkit:delegate
          - toolkit:event-observer
          - toolkit:foldable
          - toolkit:recycler-adapter
          - toolkit:statemachine
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Unit Tests ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:testDebugUnitTest

      - name: Kover ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:koverVerify

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        module:
          - toolkit:delegate
          - toolkit:event-observer
          - toolkit:foldable
          - toolkit:recycler-adapter
          - toolkit:statemachine
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:assembleRelease
