name: Pull Request

on:
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'config/**'
    paths:
      - '**.kt'
      - '**.gradle'
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

jobs:
  pre-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.publishing-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: List of Modules
        id: publishing-modules
        uses: ./.github/actions/publishing-modules

  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Lint ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:lint

      - name: Detekt ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:detekt

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Unit Tests ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:testDebugUnitTest --no-parallel

      - name: Kover ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:koverVerify

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Assemble ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:assembleRelease
