name: Pull Request

on:
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'config/**'
    paths:
      - '**.kt'
      - '**.gradle'
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

jobs:
  pre-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.read-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Read Modules
        id: read-modules
        run: |
          ./gradlew :toolkit:publishModules
          MODULES=$(cat $PWD/toolkit/build/modules.txt)
          echo "modules=$MODULES" >> "$GITHUB_OUTPUT"

  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:lint

      - name: Detekt ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:detekt

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Unit Tests ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:testDebugUnitTest

      - name: Kover ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:koverVerify

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:assembleRelease
